### ISSUE TITLE
Hire

### ISSUE THREAD

**Issue by darklordabc** [ark120202/ark120202.github.io#1]
Would you be interested in getting paid to work on my dota 2 custom game?

**Comment by ark120202** [comment]
Yes, I'm interested it it, but my decision strongly depends on what I should do and how much i'll get paid

**Comment by darklordabc** [comment]
It qould

**Comment by darklordabc** [comment]
It would pay around 11USD per hour or a per job basis. You would be doing the same stuff you have done in black star a thousand times before, e.g. custom abilities, panorama, game logic etc, whatever you prefer. What do you think?

**Comment by ark120202** [comment]
Yes, I'm really interested in it, how can I contact you?

**Comment by darklordabc** [comment]
I'm always on discord. My channel is here, but we should PM not talk in general chat. https://discord.gg/CVQagqs
